baseurl                 = "/"
DefaultContentLanguage  = "en"
title                   = "Maxx Wayne"
theme = "tactile"
preserveTaxonomyNames   = true
paginate                = 3
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = [""]

/
|_config.toml
|_...
|_themes/
|  |_tactile
|    |_layouts/
|      |_main-page.html
|_layouts
  |_main-page.html